
package Views;

import Model.ClasseRotas;
import java.awt.Color;


public class MenuSecretaria extends javax.swing.JPanel {

    public static int l;
    public static int a;
    ClasseRotas rota = new ClasseRotas();
   
    public MenuSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoVisitantes = new javax.swing.JButton();
        BotaoMembros = new javax.swing.JButton();
        BotaoIgrejas = new javax.swing.JButton();
        BotaoTipos = new javax.swing.JButton();
        BotaoCargo = new javax.swing.JButton();
        BotaoAniversariantes = new javax.swing.JButton();

        setBackground(new java.awt.Color(1, 1, 34));
        setPreferredSize(new java.awt.Dimension(171, 298));

        BotaoVisitantes.setBackground(new java.awt.Color(1, 1, 34));
        BotaoVisitantes.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BotaoVisitantes.setForeground(new java.awt.Color(255, 255, 255));
        BotaoVisitantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Businessman_26px.png"))); // NOI18N
        BotaoVisitantes.setText("Visitantes");
        BotaoVisitantes.setBorder(null);
        BotaoVisitantes.setFocusPainted(false);
        BotaoVisitantes.setFocusable(false);
        BotaoVisitantes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotaoVisitantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoVisitantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoVisitantesMouseExited(evt);
            }
        });
        BotaoVisitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVisitantesActionPerformed(evt);
            }
        });

        BotaoMembros.setBackground(new java.awt.Color(1, 1, 34));
        BotaoMembros.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BotaoMembros.setForeground(new java.awt.Color(255, 255, 255));
        BotaoMembros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Membros.png"))); // NOI18N
        BotaoMembros.setText("Membros");
        BotaoMembros.setBorder(null);
        BotaoMembros.setFocusPainted(false);
        BotaoMembros.setFocusable(false);
        BotaoMembros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotaoMembros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoMembrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoMembrosMouseExited(evt);
            }
        });
        BotaoMembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoMembrosActionPerformed(evt);
            }
        });

        BotaoIgrejas.setBackground(new java.awt.Color(1, 1, 34));
        BotaoIgrejas.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BotaoIgrejas.setForeground(new java.awt.Color(255, 255, 255));
        BotaoIgrejas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Cross_26px.png"))); // NOI18N
        BotaoIgrejas.setText("Igrejas");
        BotaoIgrejas.setBorder(null);
        BotaoIgrejas.setFocusPainted(false);
        BotaoIgrejas.setFocusable(false);
        BotaoIgrejas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotaoIgrejas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoIgrejasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoIgrejasMouseExited(evt);
            }
        });
        BotaoIgrejas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoIgrejasActionPerformed(evt);
            }
        });

        BotaoTipos.setBackground(new java.awt.Color(1, 1, 34));
        BotaoTipos.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BotaoTipos.setForeground(new java.awt.Color(255, 255, 255));
        BotaoTipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Cash_Register_20px.png"))); // NOI18N
        BotaoTipos.setText(" Tipos Contas");
        BotaoTipos.setBorder(null);
        BotaoTipos.setFocusPainted(false);
        BotaoTipos.setFocusable(false);
        BotaoTipos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotaoTipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoTiposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoTiposMouseExited(evt);
            }
        });
        BotaoTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTiposActionPerformed(evt);
            }
        });

        BotaoCargo.setBackground(new java.awt.Color(1, 1, 34));
        BotaoCargo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BotaoCargo.setForeground(new java.awt.Color(255, 255, 255));
        BotaoCargo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Collaborator_Male_26px.png"))); // NOI18N
        BotaoCargo.setText("Cargos");
        BotaoCargo.setBorder(null);
        BotaoCargo.setFocusPainted(false);
        BotaoCargo.setFocusable(false);
        BotaoCargo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotaoCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoCargoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoCargoMouseExited(evt);
            }
        });
        BotaoCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCargoActionPerformed(evt);
            }
        });

        BotaoAniversariantes.setBackground(new java.awt.Color(1, 1, 34));
        BotaoAniversariantes.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        BotaoAniversariantes.setForeground(new java.awt.Color(255, 255, 255));
        BotaoAniversariantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Birthday_Cake_26px.png"))); // NOI18N
        BotaoAniversariantes.setText("Aniversariantes");
        BotaoAniversariantes.setBorder(null);
        BotaoAniversariantes.setFocusPainted(false);
        BotaoAniversariantes.setFocusable(false);
        BotaoAniversariantes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BotaoAniversariantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoAniversariantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoAniversariantesMouseExited(evt);
            }
        });
        BotaoAniversariantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAniversariantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotaoVisitantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotaoIgrejas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotaoMembros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotaoCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotaoTipos, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
            .addComponent(BotaoAniversariantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BotaoMembros, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoAniversariantes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoIgrejas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoMembrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoMembrosMouseEntered
        BotaoMembros.setBackground(new Color(219,230,244));
    }//GEN-LAST:event_BotaoMembrosMouseEntered

    private void BotaoMembrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoMembrosMouseExited
        BotaoMembros.setBackground(new Color(1,1,34));
    }//GEN-LAST:event_BotaoMembrosMouseExited

    private void BotaoVisitantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoVisitantesMouseEntered
        BotaoVisitantes.setBackground(new Color(219,230,244));
    }//GEN-LAST:event_BotaoVisitantesMouseEntered

    private void BotaoVisitantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoVisitantesMouseExited
       BotaoVisitantes.setBackground(new Color(1,1,34));
    }//GEN-LAST:event_BotaoVisitantesMouseExited

    private void BotaoMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoMembrosActionPerformed
       TabelaMembros chamar = new TabelaMembros();
        //chamar.setLocation(5, 5);
        
         l = Principal.Painel.getWidth();
         a = Principal.Painel.getHeight();

        
        Principal.Painel.removeAll();
        Principal.Painel.add(chamar);
        Principal.Painel.revalidate();
        Principal.Painel.repaint();
        chamar.ContarMembros();
        chamar.ContarAtivos();
        chamar.ContarInativos();
        
        
        String sql = rota.getRTCadMembros();
        
        chamar.preencher(sql);
        chamar.mimx();
        chamar.paginacao();
        chamar.setSize(l, a);
    }//GEN-LAST:event_BotaoMembrosActionPerformed

    private void BotaoVisitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVisitantesActionPerformed
        TabelaVisitantes chamar = new TabelaVisitantes();

         l = Principal.Painel.getWidth();
         a = Principal.Painel.getHeight();

        
        Principal.Painel.removeAll();
        Principal.Painel.add(chamar);
        Principal.Painel.revalidate();
        Principal.Painel.repaint();
        
        String sql = rota.getRTVisitantes();
        String sq = rota.getRTHistoricoVisita();
        chamar.Povoar(sql);
        chamar.historico(sq);
        
        chamar.Povoar();
        chamar.paginacao();
        chamar.Povoarhistorico();
        chamar.paginacaoHistorico();
        
       chamar.setSize(l, a);
    }//GEN-LAST:event_BotaoVisitantesActionPerformed

    private void BotaoIgrejasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoIgrejasMouseEntered
       BotaoIgrejas.setBackground(new Color(219,230,244));
    }//GEN-LAST:event_BotaoIgrejasMouseEntered

    private void BotaoIgrejasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoIgrejasMouseExited
        BotaoIgrejas.setBackground(new Color(1,1,34));
    }//GEN-LAST:event_BotaoIgrejasMouseExited

    private void BotaoIgrejasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoIgrejasActionPerformed
        TabelaIgrejas chamar = new TabelaIgrejas();
        
        
        
         l = Principal.Painel.getWidth();
         a = Principal.Painel.getHeight();

        
        Principal.Painel.removeAll();
        Principal.Painel.add(chamar);
        Principal.Painel.revalidate();
        Principal.Painel.repaint();
        
        String sql = rota.getRTIgrejas();
        
        chamar.preencher(sql);
        
        
       chamar.setSize(l, a);
    }//GEN-LAST:event_BotaoIgrejasActionPerformed

    private void BotaoTiposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoTiposMouseEntered
        BotaoTipos.setBackground(new Color(219,230,244));
    }//GEN-LAST:event_BotaoTiposMouseEntered

    private void BotaoTiposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoTiposMouseExited
        BotaoTipos.setBackground(new Color(1,1,34));
    }//GEN-LAST:event_BotaoTiposMouseExited

    private void BotaoTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTiposActionPerformed
        TabelaTipo chamar = new TabelaTipo();

        l = Principal.Painel.getWidth();
        a = Principal.Painel.getHeight();

        Principal.Painel.removeAll();
        Principal.Painel.add(chamar);
        Principal.Painel.revalidate();
        Principal.Painel.repaint();

        String sql = rota.getRTTipo();

        chamar.Povoar(sql);
        chamar.setSize(l, a);
    }//GEN-LAST:event_BotaoTiposActionPerformed

    private void BotaoCargoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCargoMouseEntered
        BotaoCargo.setBackground(new Color(219,230,244));
    }//GEN-LAST:event_BotaoCargoMouseEntered

    private void BotaoCargoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCargoMouseExited
        BotaoCargo.setBackground(new Color(1,1,34));
    }//GEN-LAST:event_BotaoCargoMouseExited

    private void BotaoCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCargoActionPerformed
        TabelaCadCargo chamar = new TabelaCadCargo();

        l = Principal.Painel.getWidth();
        a = Principal.Painel.getHeight();

        Principal.Painel.removeAll();
        Principal.Painel.add(chamar);
        Principal.Painel.revalidate();
        Principal.Painel.repaint();

        String sql = rota.getRTCargo();

        chamar.Povoar(sql);

        chamar.setSize(l, a);
    }//GEN-LAST:event_BotaoCargoActionPerformed

    private void BotaoAniversariantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAniversariantesMouseEntered
        BotaoAniversariantes.setBackground(new Color(219,230,244));
    }//GEN-LAST:event_BotaoAniversariantesMouseEntered

    private void BotaoAniversariantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAniversariantesMouseExited
        BotaoAniversariantes.setBackground(new Color(1,1,34));
    }//GEN-LAST:event_BotaoAniversariantesMouseExited

    private void BotaoAniversariantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAniversariantesActionPerformed
        Aniversariantes ani = new Aniversariantes(null, true);
        
       ani.setVisible(true);
    }//GEN-LAST:event_BotaoAniversariantesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BotaoAniversariantes;
    public static javax.swing.JButton BotaoCargo;
    public static javax.swing.JButton BotaoIgrejas;
    public static javax.swing.JButton BotaoMembros;
    public static javax.swing.JButton BotaoTipos;
    public static javax.swing.JButton BotaoVisitantes;
    // End of variables declaration//GEN-END:variables
}
