
package com.adonaisoft.adonaisdesktop.view;

import com.adonaisoft.adonaisdesktop.view.aniversariantes.form.Aniversariantes;
import com.adonaisoft.adonaisdesktop.model.ClasseRotas;
import com.adonaisoft.adonaisdesktop.view.contatoIgrejas.list.TabelaIgrejas;
import com.adonaisoft.adonaisdesktop.view.membros.list.TabelaMembros;

import java.awt.Color;


public class MenuSecretaria extends javax.swing.JPanel {

    public static int l;
    public static int a;
    ClasseRotas rota = new ClasseRotas();
   
    public MenuSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoVisitantes = new javax.swing.JButton();
        BotaoMembros = new javax.swing.JButton();
        BotaoIgrejas = new javax.swing.JButton();
        BotaoTipos = new javax.swing.JButton();
        BotaoCargo = new javax.swing.JButton();
        BotaoAniversariantes = new javax.swing.JButton();

        setBackground(new java.awt.Color(1, 1, 34));
        setPreferredSize(new java.awt.Dimension(171, 298));




        BotaoVisitantes.setText("Visitantes");




        BotaoVisitantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoVisitantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoVisitantesMouseExited(evt);
            }
        });
        BotaoVisitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVisitantesActionPerformed(evt);
            }
        });




        BotaoMembros.setText("Membros");




        BotaoMembros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoMembrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoMembrosMouseExited(evt);
            }
        });
        BotaoMembros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoMembrosActionPerformed(evt);
            }
        });




        BotaoIgrejas.setText("Igrejas");




        BotaoIgrejas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoIgrejasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoIgrejasMouseExited(evt);
            }
        });
        BotaoIgrejas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoIgrejasActionPerformed(evt);
            }
        });




        BotaoTipos.setText(" Tipos Contas");




        BotaoTipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoTiposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoTiposMouseExited(evt);
            }
        });
        BotaoTipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTiposActionPerformed(evt);
            }
        });




        BotaoCargo.setText("Cargos");




        BotaoCargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoCargoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoCargoMouseExited(evt);
            }
        });
        BotaoCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCargoActionPerformed(evt);
            }
        });




        BotaoAniversariantes.setText("Aniversariantes");




        BotaoAniversariantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoAniversariantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoAniversariantesMouseExited(evt);
            }
        });
        BotaoAniversariantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAniversariantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BotaoVisitantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotaoIgrejas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotaoMembros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotaoCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotaoTipos, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
            .addComponent(BotaoAniversariantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BotaoMembros, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoAniversariantes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoVisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoIgrejas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoMembrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoMembrosMouseEntered

    }//GEN-LAST:event_BotaoMembrosMouseEntered

    private void BotaoMembrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoMembrosMouseExited

    }//GEN-LAST:event_BotaoMembrosMouseExited

    private void BotaoVisitantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoVisitantesMouseEntered

    }//GEN-LAST:event_BotaoVisitantesMouseEntered

    private void BotaoVisitantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoVisitantesMouseExited

    }//GEN-LAST:event_BotaoVisitantesMouseExited

    private void BotaoMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoMembrosActionPerformed
       TabelaMembros chamar = new TabelaMembros();
        //chamar.setLocation(5, 5);
        
         l = Principal.painel.getWidth();
         a = Principal.painel.getHeight();

        
        Principal.painel.removeAll();
        Principal.painel.add(chamar);
        Principal.painel.revalidate();
        Principal.painel.repaint();
        chamar.ContarMembros();
        chamar.ContarAtivos();
        chamar.ContarInativos();
        
        
        String sql = rota.getRTCadMembros();
        
        chamar.preencher(sql);
        chamar.mimx();
        chamar.paginacao();
        chamar.setSize(l, a);
    }//GEN-LAST:event_BotaoMembrosActionPerformed

    private void BotaoVisitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoVisitantesActionPerformed
        TabelaVisitantes chamar = new TabelaVisitantes();

         l = Principal.painel.getWidth();
         a = Principal.painel.getHeight();

        
        Principal.painel.removeAll();
        Principal.painel.add(chamar);
        Principal.painel.revalidate();
        Principal.painel.repaint();
        
        String sql = rota.getRTVisitantes();
        String sq = rota.getRTHistoricoVisita();
        chamar.Povoar(sql);
        chamar.historico(sq);
        
        chamar.Povoar();
        chamar.paginacao();
        chamar.Povoarhistorico();
        chamar.paginacaoHistorico();
        
       chamar.setSize(l, a);
    }//GEN-LAST:event_BotaoVisitantesActionPerformed

    private void BotaoIgrejasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoIgrejasMouseEntered

    }//GEN-LAST:event_BotaoIgrejasMouseEntered

    private void BotaoIgrejasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoIgrejasMouseExited

    }//GEN-LAST:event_BotaoIgrejasMouseExited

    private void BotaoIgrejasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoIgrejasActionPerformed
        TabelaIgrejas chamar = new TabelaIgrejas();
        
        
        
         l = Principal.painel.getWidth();
         a = Principal.painel.getHeight();

        
        Principal.painel.removeAll();
        Principal.painel.add(chamar);
        Principal.painel.revalidate();
        Principal.painel.repaint();
        
        String sql = rota.getRTIgrejas();
        
        chamar.preencher(sql);
        
        
       chamar.setSize(l, a);
    }//GEN-LAST:event_BotaoIgrejasActionPerformed

    private void BotaoTiposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoTiposMouseEntered

    }//GEN-LAST:event_BotaoTiposMouseEntered

    private void BotaoTiposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoTiposMouseExited

    }//GEN-LAST:event_BotaoTiposMouseExited

    private void BotaoTiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTiposActionPerformed
        TabelaTipo chamar = new TabelaTipo();

        l = Principal.painel.getWidth();
        a = Principal.painel.getHeight();

        Principal.painel.removeAll();
        Principal.painel.add(chamar);
        Principal.painel.revalidate();
        Principal.painel.repaint();

        String sql = rota.getRTTipo();

        chamar.Povoar(sql);
        chamar.setSize(l, a);
    }//GEN-LAST:event_BotaoTiposActionPerformed

    private void BotaoCargoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCargoMouseEntered

    }//GEN-LAST:event_BotaoCargoMouseEntered

    private void BotaoCargoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoCargoMouseExited

    }//GEN-LAST:event_BotaoCargoMouseExited

    private void BotaoCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCargoActionPerformed
        TabelaCadCargo chamar = new TabelaCadCargo();

        l = Principal.painel.getWidth();
        a = Principal.painel.getHeight();

        Principal.painel.removeAll();
        Principal.painel.add(chamar);
        Principal.painel.revalidate();
        Principal.painel.repaint();

        String sql = rota.getRTCargo();

        chamar.Povoar(sql);

        chamar.setSize(l, a);
    }//GEN-LAST:event_BotaoCargoActionPerformed

    private void BotaoAniversariantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAniversariantesMouseEntered

    }//GEN-LAST:event_BotaoAniversariantesMouseEntered

    private void BotaoAniversariantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAniversariantesMouseExited

    }//GEN-LAST:event_BotaoAniversariantesMouseExited

    private void BotaoAniversariantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAniversariantesActionPerformed
        Aniversariantes ani = new Aniversariantes(null, true);
        
       ani.setVisible(true);
    }//GEN-LAST:event_BotaoAniversariantesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton BotaoAniversariantes;
    public static javax.swing.JButton BotaoCargo;
    public static javax.swing.JButton BotaoIgrejas;
    public static javax.swing.JButton BotaoMembros;
    public static javax.swing.JButton BotaoTipos;
    public static javax.swing.JButton BotaoVisitantes;
    // End of variables declaration//GEN-END:variables
}
