/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adonaisoft.adonaisdesktop.view;

import java.awt.Color;

/**
 *
 * @author geova
 */
public class MenuConfiguracoes extends javax.swing.JPanel {

    public static int l;
    public static int a;
    public MenuConfiguracoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoIgreja = new javax.swing.JButton();
        botaoUsuario = new javax.swing.JButton();
        botaoGlobais = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(1, 1, 34));
        jPanel1.setPreferredSize(new java.awt.Dimension(98, 444));

        botaoIgreja.setBackground(new java.awt.Color(1, 1, 34));
        botaoIgreja.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        botaoIgreja.setForeground(new java.awt.Color(255, 255, 255));
        botaoIgreja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/adonaisoft/adonaisdesktop/Imagens/icons8_Menorah_26px.png"))); // NOI18N
        botaoIgreja.setText(" Igreja");
        botaoIgreja.setBorder(null);
        botaoIgreja.setFocusPainted(false);
        botaoIgreja.setFocusable(false);
        botaoIgreja.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoIgreja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoIgrejaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoIgrejaMouseExited(evt);
            }
        });
        botaoIgreja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIgrejaActionPerformed(evt);
            }
        });

        botaoUsuario.setBackground(new java.awt.Color(1, 1, 34));
        botaoUsuario.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        botaoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        botaoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/adonaisoft/adonaisdesktop/Imagens/icons8_Male_User_26px_1.png"))); // NOI18N
        botaoUsuario.setText("Usuarios");
        botaoUsuario.setBorder(null);
        botaoUsuario.setFocusPainted(false);
        botaoUsuario.setFocusable(false);
        botaoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                botaoUsuarioItemStateChanged(evt);
            }
        });
        botaoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoUsuarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoUsuarioMousePressed(evt);
            }
        });
        botaoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoUsuarioActionPerformed(evt);
            }
        });

        botaoGlobais.setBackground(new java.awt.Color(1, 1, 34));
        botaoGlobais.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        botaoGlobais.setForeground(new java.awt.Color(255, 255, 255));
        botaoGlobais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/adonaisoft/adonaisdesktop/Imagens/icons8_Settings_30px.png"))); // NOI18N
        botaoGlobais.setText("Globais");
        botaoGlobais.setBorder(null);
        botaoGlobais.setFocusPainted(false);
        botaoGlobais.setFocusable(false);
        botaoGlobais.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botaoGlobais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoGlobaisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoGlobaisMouseExited(evt);
            }
        });
        botaoGlobais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGlobaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botaoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
            .addComponent(botaoIgreja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botaoGlobais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botaoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoIgreja, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoGlobais, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIgrejaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoIgrejaMouseEntered
       botaoIgreja.setBackground(new Color(219,230,244));
    }//GEN-LAST:event_botaoIgrejaMouseEntered

    private void botaoIgrejaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoIgrejaMouseExited
        botaoIgreja.setBackground(new Color(1,1,34));
    }//GEN-LAST:event_botaoIgrejaMouseExited

    private void botaoUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoUsuarioMouseEntered
        botaoUsuario.setBackground(new Color(219,230,244));
    }//GEN-LAST:event_botaoUsuarioMouseEntered

    private void botaoUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoUsuarioMouseExited
        botaoUsuario.setBackground(new Color(1,1,34));
    }//GEN-LAST:event_botaoUsuarioMouseExited

    private void botaoIgrejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIgrejaActionPerformed
       TabelaConfiguracoes chamar = new TabelaConfiguracoes();
        
        
         l = Principal.painel.getWidth();
         a = Principal.painel.getHeight();
        
        Principal.painel.removeAll();
        Principal.painel.add(chamar);
        Principal.painel.revalidate();
        Principal.painel.repaint();
        String sql = "SELECT * FROM Configuracoes";        
        chamar.Preencher(sql);
        
       chamar.setSize(l, a);
    }//GEN-LAST:event_botaoIgrejaActionPerformed

    private void botaoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoUsuarioActionPerformed
        TabelaUsuarios chamar = new TabelaUsuarios();
       
        
        l = Principal.painel.getWidth();
        a = Principal.painel.getHeight(); 
        
        Principal.painel.removeAll();
        Principal.painel.add(chamar);
        Principal.painel.revalidate();
        Principal.painel.repaint();
        
        String sql = "SELECT CodigoUsuario,NomeUsuario FROM Usuario ORDER BY CodigoUsuario DESC";
        chamar.Povoar(sql);
        chamar.setSize(l, a);
    }//GEN-LAST:event_botaoUsuarioActionPerformed

    private void botaoGlobaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoGlobaisMouseEntered
        botaoGlobais.setBackground(new Color(219,230,244));
    }//GEN-LAST:event_botaoGlobaisMouseEntered

    private void botaoGlobaisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoGlobaisMouseExited
        botaoGlobais.setBackground(new Color(1,1,34));
    }//GEN-LAST:event_botaoGlobaisMouseExited

    private void botaoGlobaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGlobaisActionPerformed
        CadastroGlobais cha = new CadastroGlobais(null, true);
        cha.setVisible(true);
    }//GEN-LAST:event_botaoGlobaisActionPerformed

    private void botaoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoUsuarioMouseClicked
       
    }//GEN-LAST:event_botaoUsuarioMouseClicked

    private void botaoUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoUsuarioMousePressed
        
    }//GEN-LAST:event_botaoUsuarioMousePressed

    private void botaoUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_botaoUsuarioItemStateChanged
       botaoIgreja.setBackground(new Color(219,230,244));
    }//GEN-LAST:event_botaoUsuarioItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botaoGlobais;
    public static javax.swing.JButton botaoIgreja;
    public static javax.swing.JButton botaoUsuario;
    public static javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
